name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
  run: |
    xcodebuild -scheme "Countries" -destination "platform=iOS Simulator, id=5E4B5310-A6E8-43BC-AE07-1DB5DBCAD9C4, OS=16.2, name=iPhone 13" -configuration Debug build test
