name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        cd $GITHUB_WORKSPACE
        swift build --configuration debug -Xswiftc -target -Xswiftc x86_64-apple-macosx11.0
        swift test --configuration debug -Xswiftc -target -Xswiftc x86_64-apple-macosx11.0
