name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: apple/setup-swift@v2

    - name: Build
      run: swift build

    - name: Test
      run: swift test
