name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        xcodebuild -scheme "Countries" -destination "platform=macOS" -configuration Debug build test
